// lib/tech-tree/economy.ts

import type { TechNode } from '@/components/tech-tree/TechTree'

export const economyTree: TechNode[] = [
  {
    id: 'quarrying',
    name: 'Quarrying',
    level: 0,
    maxLevel: 1,
    icon: '/tech/quarrying.png',
    x: 100,
    y: 300,
    parents: [],
  },

  {
    id: 'irrigation',
    name: 'Irrigation',
    level: 0,
    maxLevel: 5,
    icon: '/tech/irrigation.png',
    x: 400,
    y: 200,
    parents: ['quarrying'],
  },
  {
    id: 'handsaw',
    name: 'Handsaw',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handsaw.png',
    x: 400,
    y: 400,
    parents: ['quarrying'],
  },

  {
    id: 'sickle',
    name: 'Sickle',
    level: 0,
    maxLevel: 5,
    icon: '/tech/sickle.png',
    x: 700,
    y: 120,
    parents: ['irrigation'],
  },
  {
    id: 'masonry',
    name: 'Masonry',
    level: 0,
    maxLevel: 5,
    icon: '/tech/masonry.png',
    x: 700,
    y: 260,
    parents: ['irrigation'],
  },
  {
    id: 'handaxe',
    name: 'Handaxe',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handaxe.png',
    x: 700,
    y: 460,
    parents: ['handsaw'],
  },

  {
    id: 'metallurgy',
    name: 'Metallurgy',
    level: 0,
    maxLevel: 1,
    icon: '/tech/metallurgy.png',
    x: 1000,
    y: 260,
    parents: ['masonry'],
  },

  {
    id: 'writing',
    name: 'Writing',
    level: 0,
    maxLevel: 5,
    icon: '/tech/writing.png',
    x: 1300,
    y: 200,
    parents: ['metallurgy'],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    level: 0,
    maxLevel: 5,
    icon: '/tech/engineering.png',
    x: 1300,
    y: 350,
    parents: ['metallurgy'],
  },

  {
    id: 'mathematics',
    name: 'Mathematics',
    level: 0,
    maxLevel: 5,
    icon: '/tech/mathematics.png',
    x: 1600,
    y: 260,
    parents: ['engineering'],
  },
  {
    id: 'coinage',
    name: 'Coinage',
    level: 0,
    maxLevel: 5,
    icon: '/tech/coinage.png',
    x: 1600,
    y: 420,
    parents: ['engineering'],
  },
]
