// lib/tech-tree/economy.ts
import type { TechNode } from '@/components/tech-tree/TechTree'

export const economyTree: TechNode[] = [
  // Column 0
  {
    id: 'quarrying',
    name: 'Quarrying',
    level: 0,
    maxLevel: 1,
    icon: '/tech/quarrying.png',
    x: 60,
    y: 300,
    parents: [],
  },

  // Column 1
  {
    id: 'irrigation',
    name: 'Irrigation',
    level: 0,
    maxLevel: 5,
    icon: '/tech/irrigation.png',
    x: 360,
    y: 200,
    parents: ['quarrying'],
  },
  {
    id: 'handsaw',
    name: 'Handsaw',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handsaw.png',
    x: 360,
    y: 360,
    parents: ['quarrying'],
  },

  // Column 2
  {
    id: 'sickle',
    name: 'Sickle',
    level: 0,
    maxLevel: 5,
    icon: '/tech/sickle.png',
    x: 660,
    y: 120,
    parents: ['irrigation'],
  },
  {
    id: 'masonry',
    name: 'Masonry',
    level: 0,
    maxLevel: 5,
    icon: '/tech/masonry.png',
    x: 660,
    y: 260,
    // ✅ BOTH REQUIRED
    parents: ['irrigation', 'handsaw'],
  },
  {
    id: 'handaxe',
    name: 'Handaxe',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handaxe.png',
    x: 660,
    y: 420,
    parents: ['handsaw'],
  },

  // Column 3
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    level: 0,
    maxLevel: 1,
    icon: '/tech/metallurgy.png',
    x: 960,
    y: 260,
    parents: ['masonry'],
  },

  // Column 4 (same “tier” as Metallurgy follow-ups)
  {
    id: 'chisel',
    name: 'Chisel',
    level: 0,
    maxLevel: 5,
    icon: '/tech/chisel.png',
    x: 1260,
    y: 120,
    parents: ['metallurgy'],
  },
  {
    id: 'writing',
    name: 'Writing',
    level: 0,
    maxLevel: 5,
    icon: '/tech/writing.png',
    x: 1260,
    y: 260,
    parents: ['metallurgy'],
  },
  {
    id: 'metalworking',
    name: 'Metalworking',
    level: 0,
    maxLevel: 5,
    icon: '/tech/metalworking.png',
    x: 1260,
    y: 420,
    parents: ['metallurgy'],
  },

  // Column 5 (right side cluster)
  {
    id: 'handcart',
    name: 'Handcart',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handcart.png',
    x: 1560,
    y: 120,
    parents: ['chisel'],
  },
  {
    id: 'multilayer_structure',
    name: 'Multilayer Structure',
    level: 0,
    maxLevel: 5,
    icon: '/tech/multilayer-structure.png',
    x: 1560,
    y: 260,
    parents: ['writing'],
  },
  {
    id: 'placer_mining',
    name: 'Placer Mining',
    level: 0,
    maxLevel: 5,
    icon: '/tech/placer-mining.png',
    x: 1560,
    y: 420,
    parents: ['metalworking'],
  },

  // Column 6 (Wheel -> Jewelry -> Plow/Sawmill)
  {
    id: 'wheel',
    name: 'Wheel',
    level: 0,
    maxLevel: 5,
    icon: '/tech/wheel.png',
    x: 1860,
    y: 80,
    parents: ['multilayer_structure'],
  },
  {
    id: 'jewelry',
    name: 'Jewelry',
    level: 0,
    maxLevel: 1,
    icon: '/tech/jewelry.png',
    x: 1860,
    y: 260,
    parents: ['wheel'],
  },
  {
    id: 'plow',
    name: 'Plow',
    level: 0,
    maxLevel: 10,
    icon: '/tech/plow.png',
    x: 2160,
    y: 180,
    parents: ['jewelry'],
  },
  {
    id: 'sawmill',
    name: 'Sawmill',
    level: 0,
    maxLevel: 10,
    icon: '/tech/sawmill.png',
    x: 2160,
    y: 340,
    parents: ['jewelry'],
  },

  // Column 7 (Engineering line)
  {
    id: 'scythe',
    name: 'Scythe',
    level: 0,
    maxLevel: 10,
    icon: '/tech/scythe.png',
    x: 2460,
    y: 120,
    parents: ['plow'],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    level: 0,
    maxLevel: 10,
    icon: '/tech/engineering.png',
    x: 2460,
    y: 260,
    parents: ['plow'],
  },
  {
    id: 'whipsaw',
    name: 'Whipsaw',
    level: 0,
    maxLevel: 10,
    icon: '/tech/whipsaw.png',
    x: 2460,
    y: 400,
    parents: ['sawmill'],
  },

  // Column 8 (Math + Coinage + Open-pit)
  {
    id: 'mathematics',
    name: 'Mathematics',
    level: 0,
    maxLevel: 10,
    icon: '/tech/mathematics.png',
    x: 2760,
    y: 260,
    parents: ['engineering'],
  },
  {
    id: 'open_pit_quarry',
    name: 'Open-pit Quarry',
    level: 0,
    maxLevel: 10,
    icon: '/tech/open-pit-quarry.png',
    x: 3060,
    y: 120,
    parents: ['mathematics'],
  },
  {
    id: 'coinage',
    name: 'Coinage',
    level: 0,
    maxLevel: 10,
    icon: '/tech/coinage.png',
    x: 3060,
    y: 400,
    parents: ['mathematics'],
  },

  // Column 9 (Stone saw / machinery / shaft mining)
  {
    id: 'stone_saw',
    name: 'Stone Saw',
    level: 0,
    maxLevel: 10,
    icon: '/tech/stone-saw.png',
    x: 3360,
    y: 80,
    parents: ['open_pit_quarry'],
  },
  {
    id: 'machinery',
    name: 'Machinery',
    level: 0,
    maxLevel: 10,
    icon: '/tech/machinery.png',
    x: 3360,
    y: 260,
    parents: ['open_pit_quarry'],
  },
  {
    id: 'shaft_mining',
    name: 'Shaft Mining',
    level: 0,
    maxLevel: 10,
    icon: '/tech/shaft-mining.png',
    x: 3360,
    y: 440,
    parents: ['coinage'],
  },

  // Column 10 (Carriage)
  {
    id: 'carriage',
    name: 'Carriage',
    level: 0,
    maxLevel: 10,
    icon: '/tech/carriage.png',
    x: 3660,
    y: 200,
    parents: ['machinery'],
  },

  // Column 11 (Cutting & Polishing)
  {
    id: 'cutting_polishing',
    name: 'Cutting & Polishing',
    level: 0,
    maxLevel: 10,
    icon: '/tech/cutting-polishing.png',
    x: 3960,
    y: 260,
    parents: ['carriage'],
  },
]
