// lib/tech-tree/economy.ts
import type { TechNode } from '@/components/tech-tree/TechTree'

const COL = 520
const ROW = 220

export const economyTree: TechNode[] = [
  // =============== PAGE 1 (Quarrying → Metallurgy) ===============
  {
    id: 'quarrying',
    name: 'Quarrying',
    level: 0,
    maxLevel: 1,
    icon: '/tech/quarrying.png',
    x: COL * 0,
    y: ROW * 1,
    parents: [],
  },
  {
    id: 'irrigation',
    name: 'Irrigation',
    level: 0,
    maxLevel: 5,
    icon: '/tech/irrigation.png',
    x: COL * 1,
    y: ROW * 0,
    parents: ['quarrying'],
  },
  {
    id: 'handsaw',
    name: 'Handsaw',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handsaw.png',
    x: COL * 1,
    y: ROW * 2,
    parents: ['quarrying'],
  },
  {
    id: 'sickle',
    name: 'Sickle',
    level: 0,
    maxLevel: 5,
    icon: '/tech/sickle.png',
    x: COL * 2,
    y: ROW * 0,
    parents: ['irrigation'],
  },
  {
    id: 'masonry',
    name: 'Masonry',
    level: 0,
    maxLevel: 5,
    icon: '/tech/masonry.png',
    x: COL * 2,
    y: ROW * 1,
    // IMPORTANT: RoK shows Masonry requires BOTH
    parents: ['irrigation', 'handsaw'],
  },
  {
    id: 'handaxe',
    name: 'Handaxe',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handaxe.png',
    x: COL * 2,
    y: ROW * 2,
    parents: ['handsaw'],
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    level: 0,
    maxLevel: 1,
    icon: '/tech/metallurgy.png',
    x: COL * 3,
    y: ROW * 1,
    parents: ['masonry'],
  },

  // =============== PAGE 2 (Metallurgy → Handcart / Multilayer / Placer) ===============
  {
    id: 'chisel',
    name: 'Chisel',
    level: 0,
    maxLevel: 5,
    icon: '/tech/chisel.png',
    x: COL * 4,
    y: ROW * 0,
    parents: ['metallurgy'],
  },
  {
    id: 'writing',
    name: 'Writing',
    level: 0,
    maxLevel: 5,
    icon: '/tech/writing.png',
    x: COL * 4,
    y: ROW * 1,
    parents: ['metallurgy'],
  },
  {
    id: 'metalworking',
    name: 'Metalworking',
    level: 0,
    maxLevel: 5,
    icon: '/tech/metalworking.png',
    x: COL * 4,
    y: ROW * 2,
    parents: ['metallurgy'],
  },
  {
    id: 'handcart',
    name: 'Handcart',
    level: 0,
    maxLevel: 5,
    icon: '/tech/handcart.png',
    x: COL * 5,
    y: ROW * 0,
    parents: ['chisel'],
  },
  {
    id: 'multilayer_structure',
    name: 'Multilayer Structure',
    level: 0,
    maxLevel: 5,
    icon: '/tech/multilayer-structure.png',
    x: COL * 5,
    y: ROW * 1,
    parents: ['writing'],
  },
  {
    id: 'placer_mining',
    name: 'Placer Mining',
    level: 0,
    maxLevel: 5,
    icon: '/tech/placer-mining.png',
    x: COL * 5,
    y: ROW * 2,
    parents: ['metalworking'],
  },

  // =============== PAGE 3 (Wheel / Jewelry / Plow / Sawmill) ===============
  {
    id: 'wheel',
    name: 'Wheel',
    level: 0,
    maxLevel: 5,
    icon: '/tech/wheel.png',
    // YOUR REQUIREMENT:
    // "Wheel behind Jewelry, but in line with Handcart (behind but higher)"
    // → Same row as Handcart, one column before Jewelry
    x: COL * 6,
    y: ROW * 0,
    parents: ['handcart'],
  },
  {
    id: 'jewelry',
    name: 'Jewelry',
    level: 0,
    maxLevel: 1,
    icon: '/tech/jewelry.png',
    x: COL * 7,
    y: ROW * 1,
    // Wheel must NOT connect to Jewelry
    parents: ['multilayer_structure'],
  },
  {
    id: 'plow',
    name: 'Plow',
    level: 0,
    maxLevel: 10,
    icon: '/tech/plow.png',
    x: COL * 8,
    y: ROW * 0,
    parents: ['jewelry'],
  },
  {
    id: 'sawmill',
    name: 'Sawmill',
    level: 0,
    maxLevel: 10,
    icon: '/tech/sawmill.png',
    x: COL * 8,
    y: ROW * 2,
    parents: ['jewelry'],
  },

  // =============== PAGE 4 (Scythe / Engineering / Whipsaw / Mathematics / Open-pit / Coinage) ===============
  {
    id: 'scythe',
    name: 'Scythe',
    level: 0,
    maxLevel: 10,
    icon: '/tech/scythe.png',
    x: COL * 9,
    y: ROW * 0,
    parents: ['plow'],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    level: 0,
    maxLevel: 10,
    icon: '/tech/engineering.png',
    x: COL * 9,
    y: ROW * 1,
    // YOU SAID: "Sawmill should connect to engineering too"
    parents: ['sawmill', 'plow'],
  },
  {
    id: 'whipsaw',
    name: 'Whipsaw',
    level: 0,
    maxLevel: 10,
    icon: '/tech/whipsaw.png',
    x: COL * 9,
    y: ROW * 2,
    parents: ['sawmill'],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    level: 0,
    maxLevel: 10,
    icon: '/tech/mathematics.png',
    x: COL * 10,
    y: ROW * 1,
    parents: ['engineering'],
  },
  {
    id: 'open_pit_quarry',
    name: 'Open-pit Quarry',
    level: 0,
    maxLevel: 10,
    icon: '/tech/open-pit-quarry.png',
    x: COL * 11,
    y: ROW * 0,
    parents: ['mathematics'],
  },
  {
    id: 'coinage',
    name: 'Coinage',
    level: 0,
    maxLevel: 10,
    icon: '/tech/coinage.png',
    x: COL * 11,
    y: ROW * 2,
    parents: ['mathematics'],
  },

  // =============== PAGE 5 (Stone Saw / Machinery / Shaft Mining / Carriage / Cutting & Polishing) ===============
  {
    id: 'stone_saw',
    name: 'Stone Saw',
    level: 0,
    maxLevel: 10,
    icon: '/tech/stone-saw.png',
    x: COL * 12,
    y: ROW * 0,
    parents: ['open_pit_quarry'],
  },
  {
    id: 'machinery',
    name: 'Machinery',
    level: 0,
    maxLevel: 10,
    icon: '/tech/machinery.png',
    x: COL * 12,
    y: ROW * 1,
    parents: ['coinage'],
  },
  {
    id: 'shaft_mining',
    name: 'Shaft Mining',
    level: 0,
    maxLevel: 10,
    icon: '/tech/shaft-mining.png',
    x: COL * 12,
    y: ROW * 2,
    parents: ['coinage'],
  },
  {
    id: 'carriage',
    name: 'Carriage',
    level: 0,
    maxLevel: 10,
    icon: '/tech/carriage.png',
    x: COL * 13,
    y: ROW * 0,
    parents: ['machinery'],
  },
  {
    id: 'cutting_polishing',
    name: 'Cutting & Polishing',
    level: 0,
    maxLevel: 10,
    icon: '/tech/cutting-polishing.png',
    x: COL * 14,
    y: ROW * 1,
    parents: ['carriage'],
  },
]
